# Generated by Django 5.0.4 on 2024-04-17 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('paste_exposure', models.CharField(choices=[('UL', 'Unlisted'), ('PB', 'Public'), ('PR', 'Private')], default='UL', max_length=10)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=250, null=True)),
                ('burn_after_reading', models.BooleanField(default=False)),
                ('password', models.BooleanField(default=False)),
                ('password_text', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
            options={
                'verbose_name_plural': 'Pastes',
            },
        ),
    ]
